package com.backend.crazy8s;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

import org.springframework.stereotype.Service;

@Service
public class LobbyService {

    private final Map<String, Room> rooms = new HashMap<>();
    private final GameService gameService;

    public LobbyService(GameService gameService) {
        this.gameService = gameService;
    }

    // Creates a new room and places the creator in slot 0.
    // playerId is generated by the LobbyController and passed in.
    public Room createRoom(String displayName, String playerId) {
        String roomCode = generateRoomCode();
        Room room = new Room(roomCode);
        room.getPlayerIds()[0] = playerId;
        room.getPlayerNames()[0] = displayName;
        rooms.put(roomCode, room);
        return room;
    }

    // Adds a player to the next open slot in the room.
    // Throws if room not found, game already started, or room is full.
    public Room joinRoom(String roomCode, String displayName, String playerId) {
        Room room = rooms.get(roomCode);
        if (room == null) throw new RuntimeException("Room not found.");
        if (!"WAITING".equals(room.getStatus())) throw new RuntimeException("Game already started.");
        int slot = room.nextOpenSlot();
        if (slot == -1) throw new RuntimeException("Room is full.");
        room.getPlayerIds()[slot] = playerId;
        room.getPlayerNames()[slot] = displayName;
        return room;
    }

    // Starts the game for a room. Minimum 2 human players.
    // Creates a GameState from the room's player configuration and saves it.
    public GameState startGame(String roomCode) {
        Room room = rooms.get(roomCode);
        if (room == null) throw new RuntimeException("Room not found.");
        if (room.humanCount() < 2) throw new RuntimeException("Need at least 2 players to start.");
        room.setStatus("IN_PROGRESS");
        GameState state = gameService.createGame(room);
        room.setGameId(state.getGameId());
        gameService.saveGame(state);
        return state;
    }

    public Room getRoom(String roomCode) {
        return rooms.get(roomCode);
    }

    // Generates a unique 4 character room code
    private String generateRoomCode() {
        String chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
        Random random = new Random();
        String code;
        do {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 4; i++) sb.append(chars.charAt(random.nextInt(chars.length())));
            code = sb.toString();
        } while (rooms.containsKey(code));
        return code;
    }
}
